### ISSUE TITLE
Build specification with menu.yml

### ISSUE THREAD

**Issue by robertodr** [bast/cmake-recipes#69]
My take on `menu.yml`:
```
appveyor:
    env:
    definitions:
    expect_failure:
        - true
        - fail_message: 'Build does not work in this case'
drone:
    env:
    definitions:
        - CMAKE_CXX_COMPILER: g++
travis:
   env:
   definitions:
       - CMAKE_CXX_COMPILER: g++
```
Three mandatory sections, with fixed names, one for each CI service we are using.
Each section has `env` and `definitions` subsections. The end goal is to avoid logical switches in the top-level script (like the one we have now for Visual Studio and Fortran)
